Lambda-School-Labs/memefly-fe

- memefly/src/Login/Login.js
- memefly/src/Login/PrivateRoute.js
- memefly/src/Login/index.js
- memefly/src/Navigation/Navigation.js
- memefly/src/Register/RegRoute.js
- memefly/src/Register/RegisterPage.js
- memefly/src/Register/SignupForm.js
- memefly/src/Register/index.js
> Initial Signin/up forms

- memefly/package.json
- memefly/src/App.css
- memefly/src/App.js
- memefly/src/Navigation/NavLoggedIn.js
- memefly/src/components/MemeMain.js
- memefly/yarn.lock
+ Styling to Nav Bar
Added some of the planned styling to Main Meme Page
Added some of the planned styling to Nav Bar
- [ x] There are no merge conflicts
> + Styling Added to Main Generate-Meme Page

- memefly/src/ImgEditorComponents/GetDimensions.js
- memefly/src/components/MemeMain.js
+ Refactored Code
Co-authored-by: dannyvidal <56495634+dannyvidal@users.noreply.github.com>
Co-authored-by: Andrew Ogle <andrewryanogle@gmail.com>
- Text now displays over image
- [x ] Complete, but not tested (may need new tests)
> + Text Overlay works

- memefly/src/LoginPage/Login.js
- memefly/src/RegisterPage/Register.js
> Revised, dynamically

- memefly/src/ImgEditor/DisplayTemplates.js
- memefly/src/ImgEditor/ImgContainer.js
- memefly/src/ImgEditor/Meme.js
- memefly/src/components/MemeMain.js
- memefly/src/components/TrendingImages. js
+ Dynamic Text resizing -Lindsey
+ Displaying all meme templates -Derek
Added Text resizing functionality to not exceed width of Meme Image
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] There are no merge conflicts
> Dynamic Text Resizing & Dynamic Template display

- memefly/src/App.css
- memefly/src/ImgEditor/DisplayTemplates.js
- memefly/src/ImgEditor/Meme.js
- memefly/src/components/MemeMain.js
- memefly/src/components/TrendingImages. js
+ Image is pushed to main when selected
+ Refactored Card Size - Lindsey
Added new functionality to the template cards.
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] My code has been reviewed by at least one peer
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] There are no merge conflicts
> + Top and bottom text appears on Images - Lindsey

- memefly/.vscode/settings.json
- memefly/package.json
- memefly/src/App.css
- memefly/src/Navigation/NavLoggedIn.js
- memefly/src/components/MemeMain.js
- memefly/yarn.lock
+ Text rendering on template - Lindsey
> + Updated all Css to Rem Units

- memefly/src/App.css
- memefly/src/Navigation/NavLoggedIn.js
- memefly/src/components/MemeMain.js
> + Styled Logged-In Nav Bar

- memefly/package.json
- memefly/src/App.css
- memefly/src/App.js
- memefly/src/Navigation/Header.js
- memefly/src/Navigation/NavCondition.js
- memefly/src/Navigation/NavLoggedIn.js
- memefly/src/Navigation/NavLoggedOut.js
- memefly/src/components/MemeMain.js
- memefly/yarn.lock
Nav bar now links to proper pages. Nav will change whether or not user is logged in.
> Derek etman

- memefly/package.json
- memefly/public/.env
- memefly/public/index.html
- memefly/src/App.css
- memefly/src/App.js
- memefly/src/LoginPage/Login.js
- memefly/src/Navigation/Header.js
- memefly/src/Navigation/NavLoggedIn.js
- memefly/src/Navigation/WelcomeTag.js
- memefly/src/RegisterPage/Register.js
- memefly/src/UserProfile/Userprofile.js
- memefly/src/components/Facebook.js
- memefly/src/components/MemeMain.js
- memefly/yarn.lock
> adding FB linking with information saving to local storage

- memefly/src/App.scss
- memefly/src/LoginPage/Login.js
- memefly/src/Navigation/NavCondition.js
- memefly/src/Navigation/NavLoggedIn.js
- memefly/src/RegisterPage/Register.js
Conditional Navigation Works based on Token flag. 
Logout button clears token
> + Conditional Navigation bar and log out button

- memefly/src/App.scss
- memefly/src/LoginPage/Login.js
- memefly/src/Navigation/Header.js
- memefly/src/Navigation/NavLoggedIn.js
- memefly/src/Navigation/NavLoggedOut.js
- memefly/src/Navigation/WelcomeTag.js
- memefly/src/RegisterPage/Register.js
> Moved Welcome Message, and other things

- memefly/public/index.html
- memefly/src/App.scss
- memefly/src/LoginPage/Login.js
- memefly/src/Navigation/NavCondition.js
- memefly/src/RegisterPage/Register.js
- memefly/src/components/Facebook.js
Changed style to facebook button, fixed log-in with facebook, will not auto load on login page load.
> + Sign in with FB hooked up.

- memefly/package.json
- memefly/src/ImgEditor/DisplayTemplates.js
- memefly/src/ImgEditor/GenerateMeme.js
- memefly/src/ImgEditor/GenerateMemePage.js
- memefly/src/ImgEditor/ImgContainer.js
- memefly/src/Navigation/NavCondition.js
- memefly/src/RegisterPage/Register.js
- memefly/src/components/Facebook.js
- memefly/src/index.js
- memefly/src/store/actions/actions.js
- memefly/src/store/reducers/index.js
- memefly/src/store/reducers/loginReducer.js
- memefly/src/store/reducers/memeReducer.js
- memefly/src/store/reducers/reducers.js
- memefly/yarn.lock
> + Set Up Redux

- memefly/src/ImgEditor/GenerateMemePage.js
- memefly/src/ImgEditor/ImgContainer.js
- memefly/src/store/actions/actions.js
- memefly/src/store/reducers/memeReducer.js
Generate meme displays randomly selected text from backend.
> Generate meme

- memefly/src/App.js
- memefly/src/App.scss
- memefly/src/ImgEditor/ImgContainer.js
- memefly/src/Navigation/NavLoggedIn.js
- memefly/src/Navigation/NavLoggedOut.js
- memefly/src/learnMore/LearnMore.js
Keeps images to a manageable size.
+ Images constrain to a max width of 500px
+ Hooked up "About us" pg
> Image constrain

- memefly/src/ImgEditor/ImgContainer.js
Changed width of text box and outlined text.
> Upload image

- memefly/src/ImgEditor/GenerateMemePage.js
- memefly/src/LoginPage/Login.js
- memefly/src/RegisterPage/Register.js
- memefly/src/store/actions/actions.js
> updated links to axios

- memefly/src/store/actions/actions.js
> fixing url for memes

- memefly/src/ImgEditor/GenerateMemePage.js
- memefly/src/ImgEditor/ImgContainer.js
- memefly/src/store/reducers/memeReducer.js
- memefly/yarn.lock
+ Saving meme works
- default image isnt showing
Bug: Default image is  hidden.
> Save Meme Progress

- memefly/src/ImgEditor/GenerateMemePage.js
+ Spacing added to image controller for style
> + Spacing added to Meme image controllers
